import { render } from "preact";
import "@fontsource-variable/inter/wght.css";
import "./app.css";
import { App } from "./app";
import { openDb } from "./db/idb";
import { createRepos } from "./db/repos";
import { configurePdfjs } from "./reader/pdf";
import { loadSettings } from "./settings";
import { initDesktop } from "./platform/desktop";
import { initFileLaunch } from "./platform/incoming";
import { registerServiceWorker } from "./platform/pwa";
import { initSync } from "./sync/sync";

configurePdfjs(new URL("./pdfjs/", document.baseURI).href);
const repos = createRepos(await openDb());
await loadSettings(repos.settings);
navigator.storage?.persist?.().catch(() => {});
await initSync(repos).catch(() => {});
render(<App repos={repos} />, document.getElementById("root")!);
initDesktop(repos);
initFileLaunch(repos);
registerServiceWorker();
